apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-bridge-config
data:
  NODE_ENV: production
  PORT: "8080"
  BSV_CHAIN: test
  STORAGE_URL: http://wallet-storage.wallet-storage-staging.svc.cluster.local:8080
  FRONTEND_URL: https://staging-auth-bridge.babbage.systems
  AUTH_BASE_URL: https://staging-auth-bridge-api.babbage.systems/auth
  BACKEND_HOST: auth-bridge-backend
  BACKEND_PORT: "8080"
