apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - certificates.yaml
  - pdb.yaml
images:
  - name: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/auth-bridge-backend
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/auth-bridge-backend
    newTag: latest
  - name: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/auth-bridge-frontend
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/auth-bridge-frontend
    newTag: latest
